<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dictionary [
<!--
    DTD for Standard Legal Term Dictionary
    Version: 2.0
    Date: April 21, 2011
-->

<!-- Element Definition ====================================================-->
<!ELEMENT Dictionary (Entry+)>
<!ATTLIST Dictionary Version CDATA #REQUIRED>
<!ELEMENT Entry (Word, Trans+)>
<!ATTLIST Entry Special CDATA #IMPLIED>
<!ATTLIST Entry bookmark ID #IMPLIED>
<!ELEMENT Word (#PCDATA)>
<!ATTLIST Word Kana CDATA #REQUIRED>
<!ELEMENT Trans (TransWord,Usage?,Example*,Note1?,Note2?, xref?)>
<!ATTLIST Trans Num CDATA #REQUIRED>
<!ELEMENT TransWord (#PCDATA)>
<!ELEMENT Usage (#PCDATA)>
<!ELEMENT Example (JaPhrase,EnPhrase,Reference?)>
<!ATTLIST Example Num CDATA #REQUIRED>
<!ELEMENT JaPhrase (#PCDATA)>
<!ELEMENT EnPhrase (#PCDATA)>
<!ELEMENT Reference (#PCDATA)>
<!ELEMENT Note1 (#PCDATA)>
<!ELEMENT Note2 (#PCDATA)>
<!ELEMENT xref EMPTY>
<!ATTLIST xref target IDREF #REQUIRED>
<!ATTLIST xref format CDATA #REQUIRED>
  ]>
<Dictionary Version="10.0">
  <Entry>
    <Word Kana="あいてがた">相手方</Word>
    <Trans Num="1">
      <TransWord>opponent</TransWord>
      <Usage>対審手続の場合</Usage>
      <Example Num="1">
        <JaPhrase>検察官、被告人又は弁護人が証人、鑑定人、通訳人又は翻訳人の尋問を請求するについては、あらかじめ、相手方に対し、その氏名及び住居を知る機会を与えなければならない</JaPhrase>
        <EnPhrase>When requesting examination of a witness, expert witness, interpreter or translator, the public prosecutor, the accused or a counsel of the accused must give the opponent an opportunity to know the name and address of that person in advance.</EnPhrase>
        <Reference>刑事訴訟法299条</Reference>
      </Example>
    </Trans>
    <Trans Num="2">
      <TransWord>the other party/other parties</TransWord>
      <Usage>一般的な場合</Usage>
      <Example Num="1">
        <JaPhrase>委任は、当事者の一方が法律行為をすることを相手方に委託し、相手方がこれを承諾することによって、その効力を生ずる</JaPhrase>
        <EnPhrase>A mandate becomes effective when one of the parties asks the other party to perform a juridical act, and the other party accepts.</EnPhrase>
        <Reference>民法643条</Reference>
      </Example>
    </Trans>
    <Trans Num="3">
      <TransWord>opposite party</TransWord>
      <Usage>一般的な場合</Usage>
      <Example Num="1">
        <JaPhrase>差止請求に係る相手方の債務の履行</JaPhrase>
        <EnPhrase>performance of obligations of the opposite party involved in a demand for an injunction</EnPhrase>
        <Reference>消費者契約法28条</Reference>
      </Example>
    </Trans>
    <Trans Num="4">
      <TransWord>counterparty</TransWord>
      <Usage>契約などの相手方</Usage>
      <Example Num="1">
        <JaPhrase>代理権を有しない者がした契約は、本人が追認をしない間は、相手方が取り消すことができる</JaPhrase>
        <EnPhrase>A contract concluded by a person without any authority to represent may be rescinded by the counterparty until the principal ratifies it</EnPhrase>
        <Reference>民法115条</Reference>
      </Example>
    </Trans>
    <Trans Num="5">
      <TransWord>adverse party</TransWord>
      <Usage>対立当事者の場合</Usage>
      <Example Num="1">
        <JaPhrase>特許権又は専用実施権の侵害に係る訴訟において、当該特許が特許無効審判により無効にされるべきものと認められるときは、特許権者又は専用実施権者は、相手方に対しその権利を行使することができない</JaPhrase>
        <EnPhrase>Where, in litigation concerning the infringement of a patent right or an exclusive registered right to work, the said patent is recognized as one that should be invalidated by a trial for patent invalidation, the rights of the patentee or the holder of the exclusive registered right to work may not be exercised against the adverse party.</EnPhrase>
        <Reference>特許法104条の3</Reference>
      </Example>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="あおいろじぎょうせんじゅうしゃ">青色事業専従者</Word>
    <Trans Num="1">
      <TransWord>family employees of a blue return taxpayer</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="あおいろしんこく（しょ）">青色申告（書）</Word>
    <Trans Num="1">
      <TransWord>blue return</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="あくいで">悪意で</Word>
    <Trans Num="1">
      <TransWord>in bad faith</TransWord>
      <Note1>【注】法律用語としての「悪意」を翻訳するとknowinglyまたはwith knowledgeとなる。しかし、法文英語にknowinglyまたはwith knowledgeをそのまま使うと誤解を招く構造になってしまうことが多い。疑問がある場合には安全のためにin bad faith を使った方が無難である。例外的に、単に「知っている」の意ではなく、「害意」に近い意味の場合がある（破産法２５３条１項２号等）。その場合にも、in bad faithを用いる。</Note1>
    </Trans>
    <Trans Num="2">
      <TransWord>knowingly</TransWord>
      <Usage>単なる認識を含む場合</Usage>
    </Trans>
    <Trans Num="3">
      <TransWord>with knowledge</TransWord>
      <Usage>単なる認識を含む場合</Usage>
    </Trans>
    <Trans Num="4">
      <TransWord>maliciously</TransWord>
      <Usage>害意に近い意味の場合</Usage>
    </Trans>
    <Trans Num="5">
      <TransWord>with malice</TransWord>
      <Usage>害意に近い意味の場合</Usage>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="あくいによるものであること">（第一項の申し立てが）悪意によるものであること（を疎明しなければならない。）</Word>
    <Trans Num="1">
      <TransWord>that the petition was filed in bad faith</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="あけわたし">明渡し</Word>
    <Trans Num="1">
      <TransWord>vacation</TransWord>
      <Usage>不動産の自主的明渡しの場合</Usage>
    </Trans>
    <Trans Num="2">
      <TransWord>eviction</TransWord>
      <Usage>不動産の強制的明渡しの場合</Usage>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="あっせん">あっせん</Word>
    <Trans Num="1">
      <TransWord>arrangement</TransWord>
      <Usage>盗品のあっせん</Usage>
      <Example Num="1">
        <JaPhrase>前項に規定する物を運搬し、保管し、若しくは有償で譲り受け、又はその有償の処分のあっせんをした者は…</JaPhrase>
        <EnPhrase>A person who transports, retains or receives with compensation or arranges disposal for compensation, property provided for in the preceding paragraph …</EnPhrase>
        <Reference>刑法第256条</Reference>
      </Example>
      <Note2>【動詞】あっせんする: arrange</Note2>
    </Trans>
    <Trans Num="2">
      <TransWord>influence</TransWord>
      <Usage>あっせん収賄</Usage>
      <Example Num="1">
        <JaPhrase>公務員が請託を受け、他の公務員に職務上不正な行為をさせるように、又は相当の行為をさせないようにあっせんすることの報酬として、賄賂を収受し、又はその要求若しくは約束をしたときは…</JaPhrase>
        <EnPhrase>A public officer who accepts, solicits or promises to accept a bribe as consideration for the influence which the official exerted or is to exert, in response to a request, upon another public officer so as to cause the other to act illegally or refrain from acting in the exercise of official duty…</EnPhrase>
        <Reference>刑法第197条の4</Reference>
      </Example>
    </Trans>
    <Trans Num="3">
      <TransWord>mediation</TransWord>
      <Usage>紛争解決のための手続</Usage>
      <Note1>【注】「あっせん」は、「第三者が紛争当事者間を仲介することにより、当事者間の自主的解決を援助、促進するための手続」である。「第三者が紛争当事者間を仲介し、双方の合意に基づく紛争解決を図る手続」である「調停」(conciliation)と一部重なるが、調停の方が積極的に当事者間に介入し、手続をリードしていくニュアンスがある。</Note1>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="あっせんいん">斡旋員</Word>
    <Trans Num="1">
      <TransWord>mediator</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="あてる">充てる</Word>
    <Trans Num="1">
      <TransWord>serve as</TransWord>
      <Usage>特定の者を役職に充てる場合</Usage>
      <Example Num="1">
        <JaPhrase>会長は、内閣総理大臣をもつて充てる</JaPhrase>
        <EnPhrase>the Prime Minister serves as chairperson</EnPhrase>
      </Example>
    </Trans>
    <Trans Num="2">
      <TransWord>is appointed from among</TransWord>
      <Usage>ある範疇の者を役職に充てる場合</Usage>
      <Example Num="1">
        <JaPhrase>本部の長は、国務大臣をもって充てる</JaPhrase>
        <EnPhrase>the chairperson of the headquarters is appointed from among the Ministers of State</EnPhrase>
      </Example>
    </Trans>
    <Trans Num="3">
      <TransWord>allocate</TransWord>
      <Usage>資金・日数等を割り当てる場合</Usage>
      <Example Num="1">
        <JaPhrase>経費に充てるため、基金を積み立てなければならない</JaPhrase>
        <EnPhrase>must establish a fund to be allocated for covering the expenses</EnPhrase>
      </Example>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="あらそい">争い</Word>
    <Trans Num="1">
      <TransWord>dispute</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いいわたし">言渡し</Word>
    <Trans Num="1">
      <TransWord>sentencing</TransWord>
      <Usage>刑事の場合</Usage>
      <Example Num="1">
        <JaPhrase>刑の言渡し</JaPhrase>
        <EnPhrase>sentencing</EnPhrase>
      </Example>
      <Note2>【動詞】言い渡す：sentence</Note2>
    </Trans>
    <Trans Num="2">
      <TransWord>rendering</TransWord>
      <Usage>刑事の場合</Usage>
      <Example Num="1">
        <JaPhrase>刑の言渡し</JaPhrase>
        <EnPhrase>rendering of sentence</EnPhrase>
      </Example>
      <Note2>【動詞】言い渡す：render</Note2>
    </Trans>
    <Trans Num="3">
      <TransWord>pronouncement</TransWord>
      <Usage>民事の場合</Usage>
      <Example Num="1">
        <JaPhrase>判決言渡し</JaPhrase>
        <EnPhrase>pronouncement of judgment</EnPhrase>
      </Example>
      <Note2>【動詞】言い渡す：pronounce</Note2>
    </Trans>
    <Trans Num="4">
      <TransWord>rendering</TransWord>
      <Usage>民事の場合</Usage>
      <Example Num="1">
        <JaPhrase>判決言渡し</JaPhrase>
        <EnPhrase>rendering of judgment</EnPhrase>
      </Example>
      <Note2>【動詞】言い渡す：render</Note2>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いいんかいせっちかいしゃ">委員会設置会社</Word>
    <Trans Num="1">
      <TransWord>company with committees</TransWord>
    </Trans>
  </Entry>
  <Entry Special="5">
    <Word Kana="…いか">…以下</Word>
    <Trans Num="1">
      <TransWord>… or less</TransWord>
      <Usage>原則</Usage>
    </Trans>
    <Trans Num="2">
      <TransWord>not more than …</TransWord>
      <Usage>上限を示すことに重点がある場合</Usage>
      <Example Num="1">
        <JaPhrase>３年以下の</JaPhrase>
        <EnPhrase>for not more than 3 years</EnPhrase>
      </Example>
    </Trans>
  </Entry>
  <Entry Special="5">
    <Word Kana="いか「…」という">以下「…」という</Word>
    <Trans Num="1">
      <TransWord>hereinafter referred to as "…"</TransWord>
    </Trans>
  </Entry>
  <Entry Special="5">
    <Word Kana="いかおなじ">以下同じ</Word>
    <Trans Num="1">
      <TransWord>the same applies hereinafter</TransWord>
    </Trans>
  </Entry>
  <Entry Special="5">
    <Word Kana="いかこの…においておなじ">以下この…において同じ</Word>
    <Trans Num="1">
      <TransWord>hereinafter the same applies in this …</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いき">遺棄</Word>
    <Trans Num="1">
      <TransWord>abandonment</TransWord>
      <Note2>【動詞】遺棄する: abandon</Note2>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぎ">異議</Word>
    <Trans Num="1">
      <TransWord>objection</TransWord>
      <Usage>原則</Usage>
    </Trans>
    <Trans Num="2">
      <TransWord>opposition</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぎごのはんけつ">異議後の判決</Word>
    <Trans Num="1">
      <TransWord>judgment subsequent to objection</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぎしゃ">異議者</Word>
    <Trans Num="1">
      <TransWord>denying party</TransWord>
    </Trans>
    <Trans Num="2">
      <TransWord>disputing party</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぎのあるさいけん">異議のある債権</Word>
    <Trans Num="1">
      <TransWord>disputed claim</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぎのもうしたて">異議の申立て</Word>
    <Trans Num="1">
      <TransWord>filing of an objection</TransWord>
      <Usage>書面による異議の場合</Usage>
    </Trans>
    <Trans Num="2">
      <TransWord>raising of an objection</TransWord>
      <Usage>口頭での異議の場合</Usage>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぎのもうしで">異議の申出</Word>
    <Trans Num="1">
      <TransWord>(filing of an) objection</TransWord>
      <Usage>書面による異議の場合</Usage>
    </Trans>
    <Trans Num="2">
      <TransWord>(raising of an) objection</TransWord>
      <Usage>口頭での異議の場合</Usage>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぎもうしたてしょ">異議申立書</Word>
    <Trans Num="1">
      <TransWord>written objection</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぎもうしたてにん">異議申立人</Word>
    <Trans Num="1">
      <TransWord>a person filing an objection</TransWord>
      <Usage>書面による意義の場合</Usage>
    </Trans>
    <Trans Num="2">
      <TransWord>a person raising an objection</TransWord>
      <Usage>口頭での意義の場合</Usage>
    </Trans>
    <Trans Num="3">
      <TransWord>opponent</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いくじ">育児</Word>
    <Trans Num="1">
      <TransWord>childcare</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いくじきゅうぎょう">育児休業</Word>
    <Trans Num="1">
      <TransWord>childcare leave</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いけん">意見</Word>
    <Trans Num="1">
      <TransWord>opinion</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いけんしょ">意見書</Word>
    <Trans Num="1">
      <TransWord>written opinion</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いけんちょうしゅ">意見聴取</Word>
    <Trans Num="1">
      <TransWord>hearing of opinions</TransWord>
    </Trans>
    <Trans Num="2">
      <TransWord>hearing</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いけんをのべる">意見を述べる</Word>
    <Trans Num="1">
      <TransWord>state one's opinion</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いごん">遺言</Word>
    <Trans Num="1">
      <TransWord>will</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いごんしっこうしゃ">遺言執行者</Word>
    <Trans Num="1">
      <TransWord>executor</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いごんしゃ">遺言者</Word>
    <Trans Num="1">
      <TransWord>testator</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いごんしょ">遺言書</Word>
    <Trans Num="1">
      <TransWord>will</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いさん">遺産</Word>
    <Trans Num="1">
      <TransWord>estate</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いさんのぶんかつ">遺産の分割</Word>
    <Trans Num="1">
      <TransWord>division of estate</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いし">意思</Word>
    <Trans Num="1">
      <TransWord>intent</TransWord>
    </Trans>
    <Trans Num="2">
      <TransWord>intention</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしつぶつ">遺失物</Word>
    <Trans Num="1">
      <TransWord>lost property</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしのうりょく">意思能力</Word>
    <Trans Num="1">
      <TransWord>mental capacity</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしひょうじ">意思表示</Word>
    <Trans Num="1">
      <TransWord>manifestation of intention</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしゃりょう">慰謝料</Word>
    <Trans Num="1">
      <TransWord>solatium</TransWord>
      <Note1>【注】（出典）所得税法施行令30条</Note1>
      <Note2>【複数形】solatia</Note2>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょう">囲障</Word>
    <Trans Num="1">
      <TransWord>fence</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょう">意匠</Word>
    <Trans Num="1">
      <TransWord>design</TransWord>
    </Trans>
  </Entry>
  <Entry Special="5">
    <Word Kana="いじょう">…以上</Word>
    <Trans Num="1">
      <TransWord>… or more</TransWord>
      <Usage>原則</Usage>
      <Example Num="1">
        <JaPhrase>２０歳以上</JaPhrase>
        <EnPhrase>20 years of age or more</EnPhrase>
      </Example>
    </Trans>
    <Trans Num="2">
      <TransWord>not less than …</TransWord>
      <Usage>下限を示すことに重点がある場合</Usage>
      <Example Num="1">
        <JaPhrase>１年以上の</JaPhrase>
        <EnPhrase>for not less than 1 year</EnPhrase>
      </Example>
    </Trans>
    <Trans Num="3">
      <TransWord>… or heavier</TransWord>
      <Usage>刑の場合</Usage>
      <Example Num="1">
        <JaPhrase>罰金以上の刑</JaPhrase>
        <EnPhrase>fine or heavier punishment</EnPhrase>
      </Example>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょうけん">意匠権</Word>
    <Trans Num="1">
      <TransWord>design right</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょうけんしゃ">意匠権者</Word>
    <Trans Num="1">
      <TransWord>holder of a design right</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょうげんぼ">意匠原簿</Word>
    <Trans Num="1">
      <TransWord>design register</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょうこうほう">意匠公報</Word>
    <Trans Num="1">
      <TransWord>design bulletin</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょうとうろく">意匠登録</Word>
    <Trans Num="1">
      <TransWord>design registration</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょうとうろくしゅつがん">意匠登録出願</Word>
    <Trans Num="1">
      <TransWord>application for design registration</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょうとうろくしょう">意匠登録証</Word>
    <Trans Num="1">
      <TransWord>certificate of design registration</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょうのそうさくをしたもの">意匠の創作をした者</Word>
    <Trans Num="1">
      <TransWord>creator of a design</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いしょく">委嘱</Word>
    <Trans Num="1">
      <TransWord>commission</TransWord>
      <Note2>【動詞】委嘱する: commission</Note2>
    </Trans>
    <Trans Num="2">
      <TransWord>entrustment</TransWord>
      <Note2>【動詞】委嘱する: entrust</Note2>
    </Trans>
    <Trans Num="3">
      <TransWord>delegation</TransWord>
      <Note2>【動詞】委嘱する: delegate</Note2>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いそう">移送</Word>
    <Trans Num="1">
      <TransWord>transfer</TransWord>
      <Note2>【動詞】移送する: transfer</Note2>
    </Trans>
    <Trans Num="2">
      <TransWord>transportation</TransWord>
      <Note2>【動詞】移送する: transport</Note2>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぞう">遺贈</Word>
    <Trans Num="1">
      <TransWord>testamentary gift</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いそうのさいばん">移送の裁判</Word>
    <Trans Num="1">
      <TransWord>decision of transfer</TransWord>
    </Trans>
    <Trans Num="2">
      <TransWord>decision to transfer</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぞく">遺族</Word>
    <Trans Num="1">
      <TransWord>surviving family (member)</TransWord>
      <Usage>個々の遺族を指す場合</Usage>
    </Trans>
    <Trans Num="2">
      <TransWord>bereaved family</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぞくきそねんきん">遺族基礎年金</Word>
    <Trans Num="1">
      <TransWord>basic pension for surviving family</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぞくほしょういちじきん">遺族補償一時金</Word>
    <Trans Num="1">
      <TransWord>lump sum compensation for surviving family</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いぞくほしょうねんきんまえばらいいちじきん">遺族補償年金前払一時金</Word>
    <Trans Num="1">
      <TransWord>compensation pension advance for surviving family</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いたく">委託</Word>
    <Trans Num="1">
      <TransWord>entrustment</TransWord>
    </Trans>
    <Trans Num="2">
      <TransWord>consignment</TransWord>
    </Trans>
    <Trans Num="3">
      <TransWord>delegation</TransWord>
      <Usage>（信託法・信託業法における）権限の委託</Usage>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いたくけいやく">委託契約</Word>
    <Trans Num="1">
      <TransWord>service agreement</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いたくしゃ">委託者</Word>
    <Trans Num="1">
      <TransWord>requesting party</TransWord>
    </Trans>
    <Trans Num="2">
      <TransWord>delegating party</TransWord>
    </Trans>
    <Trans Num="3">
      <TransWord>entrustor</TransWord>
      <Usage>その他の事務の委託</Usage>
    </Trans>
    <Trans Num="4">
      <TransWord>settlor</TransWord>
      <Usage>信託</Usage>
    </Trans>
    <Trans Num="5">
      <TransWord>consignor</TransWord>
      <Usage>販売・運送等の委託</Usage>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いたくしゃさしずがたとうししんたく">委託者指図型投資信託</Word>
    <Trans Num="1">
      <TransWord>investment trust with settlor's instructions</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いたくしゃひさしずがたとうししんたく">委託者非指図型投資信託</Word>
    <Trans Num="1">
      <TransWord>investment trust without settlor's instructions</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いたくする">委託する</Word>
    <Trans Num="1">
      <TransWord>request</TransWord>
      <Usage>一般に委託する場合</Usage>
    </Trans>
    <Trans Num="2">
      <TransWord>ask</TransWord>
      <Usage>一般に委託する場合</Usage>
    </Trans>
    <Trans Num="3">
      <TransWord>delegate</TransWord>
      <Usage>権限を代わって行使することを委託する場合</Usage>
    </Trans>
    <Trans Num="4">
      <TransWord>entrust</TransWord>
      <Usage>信認関係の下で事務を委託する場合</Usage>
    </Trans>
    <Trans Num="5">
      <TransWord>consign</TransWord>
      <Usage>商品の販売を委託する場合</Usage>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いたくりょうきん">委託料金</Word>
    <Trans Num="1">
      <TransWord>commission</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いちじきん">一時金</Word>
    <Trans Num="1">
      <TransWord>lump sum payment</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いちじひご">一時庇護</Word>
    <Trans Num="1">
      <TransWord>temporary refuge</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いちじしょとく">一時所得</Word>
    <Trans Num="1">
      <TransWord>occasional income</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いちじるしい">著しい</Word>
    <Trans Num="1">
      <TransWord>extreme</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いちじるしいそんがいまたはちたい">著しい損害又は遅滞</Word>
    <Trans Num="1">
      <TransWord>extreme harm or delay </TransWord>
      <Example Num="1">
        <JaPhrase>裁判所は、著しい損害又は遅滞を避けるため必要があると認めるときは、…</JaPhrase>
        <EnPhrase>When the court finds it is necessary for avoiding extreme harm or delay,…</EnPhrase>
        <Reference>会社法835条</Reference>
      </Example>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いちぶかいせい">一部改正</Word>
    <Trans Num="1">
      <TransWord>partial amendment</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっかつばいきゃく">一括売却</Word>
    <Trans Num="1">
      <TransWord>disposal by a sale en bloc</TransWord>
      <Note1>【注】（出典）破産法78条2項4号</Note1>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっしんせんぞくせい">一身専属性</Word>
    <Trans Num="1">
      <TransWord>personal nature</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんいぎしんじゅつきかん">一般異議申述期間</Word>
    <Trans Num="1">
      <TransWord>ordinary period for making objections</TransWord>
      <Note1>【注】（出典）民事再生法222条3項</Note1>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんざいだんほうじん">一般財団法人</Word>
    <Trans Num="1">
      <TransWord>general incorporated foundation</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんしゃだんほうじん">一般社団法人</Word>
    <Trans Num="1">
      <TransWord>general incorporated association</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんしょうけいにん">一般承継人</Word>
    <Trans Num="1">
      <TransWord>general successor</TransWord>
      <Example Num="1">
        <JaPhrase>前項の規定による請求は、…一般承継人と共同してしなければならない</JaPhrase>
        <EnPhrase>requests pursuant to the provisions of the preceding paragraph must be made jointly …with the person's general successors</EnPhrase>
        <Reference>会社法133条2項</Reference>
      </Example>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんしょうひしゃ">一般消費者</Word>
    <Trans Num="1">
      <TransWord>general consumers</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんしょく">一般職</Word>
    <Trans Num="1">
      <TransWord>regular service</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんちょうさきかん">一般調査期間</Word>
    <Trans Num="1">
      <TransWord>ordinary period for investigation</TransWord>
      <Note1>【注】（出典）破産法112条</Note1>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんちょうさきじつ">一般調査期日</Word>
    <Trans Num="1">
      <TransWord>ordinary date of investigation</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんにこうせいとみとめられるきぎょうかいけいのきじゅん">一般に公正妥当と認められる企業会計の基準</Word>
    <Trans Num="1">
      <TransWord>business accounting standards generally accepted as fair and appropriate</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんのさきどりとっけん">一般の先取特権</Word>
    <Trans Num="1">
      <TransWord>general statutory lien</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんのゆうせんけんがあるさいけん">一般の優先権がある債権</Word>
    <Trans Num="1">
      <TransWord>general priority claim</TransWord>
      <Note1>【注】（出典）民事再生法122条1項</Note1>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いっぱんべんさいきかん">一般弁済期間</Word>
    <Trans Num="1">
      <TransWord>general period for payment</TransWord>
      <Note1>【注】（出典）民事再生法199条</Note1>
    </Trans>
  </Entry>
  <Entry Special="5">
    <Word Kana="いつわりそのたふせいのこうい">偽りその他不正の行為</Word>
    <Trans Num="1">
      <TransWord>deception or other wrongful act</TransWord>
    </Trans>
  </Entry>
  <Entry Special="5">
    <Word Kana="いつわりそのたふせいのしゅだん">偽りその他不正の手段</Word>
    <Trans Num="1">
      <TransWord>deception or other wrongful means</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いてん">移転</Word>
    <Trans Num="1">
      <TransWord>transfer</TransWord>
      <Usage>権利等の移転</Usage>
      <Example Num="1">
        <JaPhrase>鉱業権、工業所有権その他これらに類する権利の移転</JaPhrase>
        <EnPhrase>transfer of the mining right, industrial property right or other right similar thereto</EnPhrase>
        <Reference>外国為替令14条1項4号</Reference>
      </Example>
    </Trans>
    <Trans Num="2">
      <TransWord>relocation</TransWord>
      <Usage>主たる事務所の移転など</Usage>
      <Example Num="1">
        <JaPhrase>支店の設置、移転及び廃止</JaPhrase>
        <EnPhrase>The establishment, relocation and abolition of branch offices</EnPhrase>
        <Reference>会社法482条3項2号</Reference>
      </Example>
    </Trans>
    <Trans Num="3">
      <TransWord>removal</TransWord>
      <Usage>人・物の場所的な移動など</Usage>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いでんしくみかえせいぶつ">遺伝子組換え生物</Word>
    <Trans Num="1">
      <TransWord>genetically modified organism</TransWord>
      <Usage>原則</Usage>
      <Note1>【注】（出典）生物多様性条約</Note1>
    </Trans>
    <Trans Num="2">
      <TransWord>living modified organism</TransWord>
      <Usage>食物等を含まない場合</Usage>
      <Note1>【注】（出典）カルタヘナ議定書</Note1>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いでんしくみかえびせいぶつ">遺伝子組換え微生物</Word>
    <Trans Num="1">
      <TransWord>genetically modified microorganism</TransWord>
      <Usage>原則</Usage>
    </Trans>
    <Trans Num="2">
      <TransWord>modified microorganisms</TransWord>
      <Usage>食物等を含まない場合</Usage>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いにん">委任</Word>
    <Trans Num="1">
      <TransWord>mandate</TransWord>
      <Usage>民法上の委任契約</Usage>
      <Example Num="1">
        <JaPhrase>委任は、当事者の一方が法律行為をすることを相手方に委託し、相手方がこれを承諾することによって、その効力を生ずる。</JaPhrase>
        <EnPhrase>A mandate becomes effective when one of the parties mandates the other party to perform a juridical act, and the other party accepts the mandate.</EnPhrase>
        <Reference>民法第643条</Reference>
      </Example>
    </Trans>
    <Trans Num="2">
      <TransWord>delegation</TransWord>
      <Usage>権限の委任という意味での委任</Usage>
      <Example Num="1">
        <JaPhrase>ある種類又は特定の事項の委任を受けた使用人</JaPhrase>
        <EnPhrase>Employees to Whom the Authority for a Certain Kind of Matter or a Specific Matter Is Delegated</EnPhrase>
        <Reference>会社法14条</Reference>
      </Example>
    </Trans>
    <Trans Num="3">
      <TransWord>entrustment</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いにんじむ">委任事務</Word>
    <Trans Num="1">
      <TransWord>delegated business</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いにんじょう">委任状</Word>
    <Trans Num="1">
      <TransWord>power of attorney</TransWord>
    </Trans>
    <Trans Num="2">
      <TransWord>proxy</TransWord>
      <Usage>会社法関係や会議の代理委任状</Usage>
      <Note1>【注】（出典）商法26条</Note1>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いにんによるだいりにん">委任による代理人</Word>
    <Trans Num="1">
      <TransWord>privately appointed agent</TransWord>
      <Example Num="1">
        <JaPhrase>委任による代理人は、…復代理人を選任することができない</JaPhrase>
        <EnPhrase>A privately appointed agent may not appoint a sub-agent …</EnPhrase>
        <Reference>民法104条</Reference>
      </Example>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いはく">威迫</Word>
    <Trans Num="1">
      <TransWord>intimidation</TransWord>
      <Note2>【動詞】威迫する: intimidate</Note2>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いはん">違反</Word>
    <Trans Num="1">
      <TransWord>violation</TransWord>
      <Example Num="1">
        <JaPhrase>違反事件</JaPhrase>
        <EnPhrase>a case of violation</EnPhrase>
        <Reference>出入国管理及び難民認定法31条</Reference>
      </Example>
      <Note2>【動詞】違反する: violate</Note2>
    </Trans>
    <Trans Num="2">
      <TransWord>offense</TransWord>
      <Note2>【動詞】違反する: offend</Note2>
    </Trans>
    <Trans Num="3">
      <TransWord>contravention</TransWord>
      <Example Num="1">
        <JaPhrase>第三十五条第一項の規定に違反して財務諸表等を備えて置かず、財務諸表等に記載すべき事項を記載せず、若しくは虚偽の記載をし、</JaPhrase>
        <EnPhrase>a person who fails to prepare financial statements, etc., fails to record necessary items or makes false records contravening the provisions of Article 35, paragraph1</EnPhrase>
        <Reference>工業標準化法74条2号</Reference>
      </Example>
      <Note2>【動詞】違反する: contravene</Note2>
    </Trans>
    <Trans Num="4">
      <TransWord>breach</TransWord>
      <Example Num="1">
        <JaPhrase>秘密保持命令違反の罪</JaPhrase>
        <EnPhrase>Crime of breach of protective order</EnPhrase>
        <Reference>特許法200条の2</Reference>
      </Example>
      <Note2>【動詞】違反する: breach</Note2>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いはんこうい">違反行為</Word>
    <Trans Num="1">
      <TransWord>violation</TransWord>
    </Trans>
    <Trans Num="2">
      <TransWord>illegal conduct</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いはんちょうさ">違反調査</Word>
    <Trans Num="1">
      <TransWord>investigation into violation</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いふ（する）">委付（する）</Word>
    <Trans Num="1">
      <TransWord>abandonment (abandon)</TransWord>
    </Trans>
  </Entry>
  <Entry>
    <Word Kana="いほうな">違法な</Word>
    <Trans Num="1">
      <TransWord>illegal</TransWord>
      <Example Num="1">
        <JaPhrase>違法行為等の是正</JaPhrase>
        <EnPhrase>Rectification of Illegal Acts, etc.</EnPhrase>
        <Reference>日本銀行法56条タイトル</Reference>
      </Example>
    </Trans>
    <Trans Num="2">